

version: '3.1'

services:

  mongo:
    image: mongo:3.6
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ot6

  bootcamp:
    image: alefh/demo-docker-ot6:2.0
    ports:
      - "9093:8080"
    environment:
      DB_HOST: mongo
      DB_PORT: 27017
      DB_PASS: ot6
      DB_USER: root
      DB_NAME: bootcamp
    restart: on-failure
    depends_on:
      - mongo
